version-template: "$MAJOR.$MINOR.$PATCH"
name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
template: |
  # What's Changed
  $CHANGES

categories:
  - title: "⚡ Release"
    label: "major"
  - title: "🚀 New Features"
    label: "minor"
  - title: "🐞 Bug Fixes"
    label: "patch"

version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"

include-labels:
  - "major"
  - "minor"
  - "patch"
